# CC=gcc
# CFLAGS=-I. -I.. $(OPTFLAGS)
# LIBS=$(OPTLIBS)
# SOURCES=main.cpp
# #$(wildcard src/**/*.c src/*.c)
# OBJECTS=$(patsubst %.c,%.o,$(SOURCES))

# %.o: %.c $(SOURCES)
# 	$(CC) -c -o $@ $< $(CFLAGS)

# altair8800: $(OBJECTS)
# 	$(CC) -o $@ $^ $(CFLAGS)
